# Generated by Django 2.1 on 2018-09-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_or_block_identifier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_name',
        ),
    ]
