# Generated by Django 2.1 on 2018-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='House or Block number, street number or name, district name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10 digits only. E.g 0552233444', max_length=10, null=True),
        ),
    ]
