# Generated by Django 2.1 on 2018-09-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0005_auto_20180916_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Required. House or Block number, street number or name, district name\nE.g: Villa 22, street 10B, Al Quoz 2', max_length=100, null=True),
        ),
    ]
