# Generated by Django 2.1 on 2018-09-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0007_auto_20180918_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
