# Generated by Django 2.1 on 2018-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0010_auto_20180923_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
