# Generated by Django 2.1 on 2018-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0011_auto_20180923_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='gemstones_used',
            field=models.CharField(blank=True, choices=[('n', 'Not set'), ('r', 'Ruby'), ('d', 'Diamond'), ('s', 'Saphire'), ('j', 'Jade'), ('p', 'Pearl'), ('a', 'Amethyst')], default='n', help_text='Gemstones, like ruby or saphire, used in this item', max_length=1),
        ),
    ]
