# Generated by Django 2.1 on 2018-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0012_auto_20180923_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='jewelry_gallery'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='jewelry_gallery'),
        ),
    ]
