# Generated by Django 2.1 on 2018-09-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0013_auto_20180923_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
