# Generated by Django 2.1 on 2018-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0014_auto_20180923_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='jewelry-gallery'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='jewelry-gallery'),
        ),
    ]
