# Generated by Django 2.1 on 2018-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0015_auto_20180923_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='gemstones_used',
            field=models.CharField(blank=True, choices=[('r', 'Ruby'), ('d', 'Diamond'), ('s', 'Saphire'), ('j', 'Jade'), ('p', 'Pearl'), ('a', 'Amethyst')], default='r', help_text='Gemstones, like ruby or saphire, used in this item', max_length=1),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='metallic_finish',
            field=models.CharField(blank=True, choices=[('t', 'Stainless Steel'), ('s', 'Silver'), ('g', 'Gold'), ('r', 'Rose Gold'), ('p', 'Platinum')], default='t', help_text='Metal the jewelry is made from', max_length=1),
        ),
    ]
