# Generated by Django 2.1 on 2018-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0016_auto_20180923_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='category',
            field=models.CharField(blank=True, choices=[('e', 'Earring'), ('r', 'Ring'), ('n', 'Necklace'), ('p', 'Pendant'), ('b', 'Braces')], default='r', help_text='The type of jewelry this belongs to', max_length=1),
        ),
    ]
