# Generated by Django 2.1 on 2018-09-28 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0018_auto_20180927_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
