# Generated by Django 2.1 on 2018-09-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0019_auto_20180928_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='jewelry_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.ShoppingCart'),
        ),
    ]
