# Generated by Django 2.1 on 2018-09-28 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0021_auto_20180928_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
