# Generated by Django 2.1 on 2018-09-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0022_auto_20180928_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='title',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='jewelry_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.Jewelry'),
        ),
    ]
