# Generated by Django 2.1 on 2018-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0023_auto_20180928_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='jewelry_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='jewelry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
