# Generated by Django 2.1 on 2018-09-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0025_cartitem_jewelry_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='jewelry_id',
        ),
    ]
