# Generated by Django 2.1 on 2018-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0026_remove_cartitem_jewelry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(default=1, editable=False, help_text='The number of jewelry items of the same type added to the shopping cart'),
        ),
    ]
