# Generated by Django 2.1 on 2018-09-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelryapp', '0027_cartitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="The total price of this type of item. It's count multiplied by its unit price", max_digits=8),
        ),
    ]
