# Generated by Django 2.1 on 2018-09-30 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jewelryapp', '0028_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when the order was placed')),
                ('user', models.ForeignKey(help_text='The user that placed the order. I.e. The shopper.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, editable=False, help_text='The number of jewelry items of the same type ordered')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, help_text="The total price of this type of item. It's count multiplied by its unit price", max_digits=8)),
                ('jewelry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.Jewelry')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelryapp.Order')),
            ],
        ),
    ]
